apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: busybox
        image: busybox
        args:
        - /bin/sh
        - -c
        - >
          while true; do
            date >> /shared/data.txt;
            sleep 5;
          done
        volumeMounts:
        - name: shared-data
          mountPath: /shared
      - name: multitool
        image: praqma/network-multitool
        volumeMounts:
        - name: shared-data
          mountPath: /shared
